{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-client
  namespace: {{ .Release.Namespace }}
data:
  linstor-client.conf: |+
    [global]
      {{- if not .Values.controller.ssl.enabled }}
      controllers = linstor://localhost:{{ .Values.controller.port }},linstor://{{ $fullName }}-controller:{{ .Values.controller.port }}
      {{- else }}
      controllers = linstor+ssl://localhost:{{ .Values.controller.ssl.port }},linstor+ssl://{{ $fullName }}-controller:{{ .Values.controller.ssl.port }}
      certfile = /tls/tls.crt
      keyfile = /tls/tls.key
      cafile = /tls/ca.crt
      {{- end }}
{{- end }}
