{{- $fullName := include "linstor.fullname" . -}}
{{- $config := include "linstor.controllerConfig" . -}}
{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "linstor.fullname" . }}-controller
data:
  linstor.toml: {{ $config | b64enc }}
{{- end }}
