{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-controller
  namespace: {{ .Release.Namespace }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: restapi
    port: {{ .Values.controller.port }}
  - name: ssl
    port: {{ .Values.controller.ssl.port }}
  # NOTE: No selector here! A selector would automatically add all matching and ready pods to the endpoint
{{- end }}
