{{- $fullName := include "linstor.fullname" . -}}
{{- $cn := printf "%s-satellite" $fullName -}}
{{- if .Values.satellite.enabled }}
{{- if .Values.satellite.ssl.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-satellite-tls
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "directives.qbec.io/update-policy": "never"
type: kubernetes.io/tls
data:
  {{- with genSelfSignedCert $cn nil nil 3650 }}
  tls.crt: {{ b64enc .Cert }}
  tls.key: {{ b64enc .Key }}
  {{- end }}
{{- end }}
{{- end }}
