{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.satellite.enabled }}
{{- if or .Values.satellite.overwriteDrbdConf .Values.satellite.ssl.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-satellite
data:
  {{- if .Values.satellite.overwriteDrbdConf }}
  drbd.conf: |+
    include "drbd.d/global_common.conf";
    include "drbd.d/*.res";

  global_common.conf: |+
    global {
     usage-count no;
     udev-always-use-vnr;
    }
    common {
     handlers {
     }
     startup {
     }
     options {
     }
     disk {
     }
     net {
     }
    }
  {{- end }}
  linstor_satellite.toml: |+
    [netcom]
      {{- if not .Values.satellite.ssl.enabled }}
      port={{ .Values.satellite.port }}
      {{- else }}
      type="ssl"
      port={{ .Values.satellite.ssl.port }}
      server_certificate="/config/ssl/keystore.jks"
      trusted_certificates="/config/ssl/certificates.jks"
      key_password="linstor"
      keystore_password="linstor"
      truststore_password="linstor"
      ssl_protocol="TLSv1.2"
      {{- end }}
{{- end }}
{{- end }}
