# ------------------------------------------------------------------------------
# Linstor-controller is main control point for Linstor, it provides API for
# clients and communicates with satellites for creating and monitor DRBD-devices
# ------------------------------------------------------------------------------

controller:
  enabled: true
  image:
    repository: docker.io/kvaps/linstor-controller
    tag: v1.11.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  replicaCount: 2

  port: 3370
  ssl:
    enabled: true
    port: 3371

  #hostNetwork: true

  service:
    annotations:
      prometheus.io/path: "/metrics?error_reports=false"
      prometheus.io/port: "3370"
      prometheus.io/scrape: "true"

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
  
  initSettings:
    enabled: false
    # Set plain connector listen to localhost 
    plainConnectorBindAddress: "127.0.0.1"
    # Disable user security (required for setting global options)
    disableUserSecurity: true

  # Database config
  db:
    user: linstor
    password: linstor
    connectionUrl: jdbc:h2:/data/linstordb

  # PostgreSQL example
  # db:
  #   user: linstor
  #   password: linstor
  #   connectionUrl: jdbc:postgresql://linstor-db-stolon-proxy/linstor

  # Etcd example
  # db:
  #   connectionUrl: etcd://node1:2379,node2:2379
  #   tls: true
  #   cert: |
  #     -----BEGIN CERTIFICATE-----
  #     MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
  #   key: |
  #     -----BEGIN RSA PRIVATE KEY-----
  #     MIIEpAIBAAKCAQEA0xRXCs7WUhmHZ ...
  #   ca: |
  #     -----BEGIN CERTIFICATE-----
  #     MIIDDzCCAfegAwIBAgIRAKTcgKx3g ...
  #   etcdPrefix: "/LINSTOR/"

# ------------------------------------------------------------------------------
# Linstor-satellites run on every node, they listen and perform controller tasks
# They operates directly with LVM and ZFS subsystems
# ------------------------------------------------------------------------------

satellite:
  enabled: true
  image:
    repository: docker.io/kvaps/linstor-satellite
    tag: v1.11.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  port: 3366
  ssl:
    enabled: true
    port: 3367

  # Oerwrite drbd.conf and global_common.conf files. This option will enable
  # usage-count=no and udev-always-use-vnr options by default
  overwriteDrbdConf: true

  # How many nodes can simultaneously download new image
  update:
    maxUnavailable: 40

  # nodeSelector:
  #   linstor-satellite: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

# ------------------------------------------------------------------------------
# Linstor CSI driver provides compatibility level for adding Linstor support
# for Kubernetes
# ------------------------------------------------------------------------------

csi:
  enabled: true
  image:
    pullSecrets:
      - name: regsecret
    linstorCsiPlugin:
      repository: docker.io/kvaps/linstor-csi
      tag: v1.11.1
      pullPolicy: IfNotPresent
    csiProvisioner:
      repository: k8s.gcr.io/sig-storage/csi-provisioner
      tag: v2.0.4
      pullPolicy: IfNotPresent
    csiAttacher:
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: v3.0.2
      pullPolicy: IfNotPresent
    csiResizer:
      repository: k8s.gcr.io/sig-storage/csi-resizer
      tag: v1.0.1
      pullPolicy: IfNotPresent
    csiSnapshotter:
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: v3.0.2
      pullPolicy: IfNotPresent
    csiNodeDriverRegistrar:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v2.0.1
      pullPolicy: IfNotPresent
    csiLivenessProbe:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.1.0
      pullPolicy: IfNotPresent

  controller:
    replicaCount: 2

    csiProvisioner:
      topology: false

    # nodeSelector:
    #   node-role.kubernetes.io/master: ""
    
    # tolerations:
    #   - key: node-role.kubernetes.io/master
    #     operator: Exists
    #     effect: NoSchedule

  node: {}
    # nodeSelector:
    #   linstor-satellite: ""
    
    # tolerations:
    #   - key: node-role.kubernetes.io/master
    #     operator: Exists
    #     effect: NoSchedule

haController:
  enabled: true
  image:
    repository: docker.io/kvaps/linstor-ha-controller
    tag: v1.11.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  replicaCount: 2

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

# ------------------------------------------------------------------------------
# Stork is a scheduler extender plugin for Kubernetes which allows a storage
# driver to give the Kubernetes scheduler hints about where to place a new pod
# so that it is optimally located for storage performance
# ------------------------------------------------------------------------------

stork:
  enabled: true
  image:
    repository: docker.io/kvaps/linstor-stork
    tag: v1.11.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  replicaCount: 2

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

storkScheduler:
  enabled: true
  image:
    repository: k8s.gcr.io/kube-scheduler
    tag: v1.20.1
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  replicaCount: 2

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
